### ISSUE TITLE
ModuleNotFoundError: No module named 'lvis'

### ISSUE THREAD

**Issue by tangmingsh** [cloud-annotations/google-colab-training#2]
Hi there,

I run object_detection.ipynb on google-colab
when I train the model
```
!rm -rf $OUTPUT_PATH
!python -m object_detection.model_main \
    --pipeline_config_path=$DATA_PATH/pipeline.config \
    --model_dir=$OUTPUT_PATH \
    --num_train_steps=$NUM_TRAIN_STEPS \
    --num_eval_steps=100
```
I shows errors as below:

>Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/models/research/object_detection/model_main.py", line 25, in <module>
    from object_detection import model_lib
  File "/content/models/research/object_detection/model_lib.py", line 29, in <module>
    from object_detection import eval_util
  File "/content/models/research/object_detection/eval_util.py", line 36, in <module>
    from object_detection.metrics import lvis_evaluation
  File "/content/models/research/object_detection/metrics/lvis_evaluation.py", line 23, in <module>
    from lvis import results as lvis_results
ModuleNotFoundError: No module named 'lvis'

How to solve this problem,Thanks.

**Comment by tangmingsh** [comment]
After the installation of lvis python library, ModuleNotFoundError: No module named 'lvis' error will be solved.

```
pip install lvis
```

**Comment by bourdakos1** [comment]
@tangmingsh thanks for pointing this out! should be fixed now :)
